//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dan_LI_Bojana_Backo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        public int PatientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JMBG { get; set; }
        public string HealthIsuranceNumber { get; set; }
        public string Username { get; set; }
        public string UserPassword { get; set; }
        public int DoctorID { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
    }
}
